sudo: required

language: csharp

branches:
  only:
  - master

addons:
  ssh_known_hosts:
  - 159.203.33.172
  apt:
    packages:
    - sshpass

cache:
  directories:
  - $HOME/packages

services:
  - docker

script:
  - export TRAVIS_BUILD_DIRECTORY=$PWD
#  - docker build -t webapp:test -f dockerfiles/test .
#  - docker run -it -v $HOME/packages:/root/.nuget/packages -v $PWD/publish:/root/publish webapp:test

after_success:
  - cd $TRAVIS_BUILD_DIRECTORY
#  - docker build -t xaviercl/webapp:latest -f dockerfiles/release .
#  - docker login -u="$DOCKER_HUB_USERNAME" -p="$DOCKER_HUB_PASSWORD"
#  - docker push xaviercl/webapp:latest
#  - ssh-keygen -t rsa -f $HOME/.ssh/testServerWebapp -N ''
#  - echo "$TEST_SERVER_RSA_PRIVATE_KEY" >> ~/.ssh/id_rsa
#  - chmod 600 ~/.ssh/id_rsa
#  - echo "$TEST_SERVER_RSA_PUBLIC_KEY" >> ~/.ssh/id_rsa.pub
#  - chmod 600 ~/.ssh/id_rsa.pub
#  - echo "$KNOWN_HOST_TEST_SERVER" >> ~/.ssh/known_hosts
#  - chmod 600 ~/.ssh/known_hosts
#  - echo "$TEST_SERVER_RSA_PRIVATE_KEY"
#  - echo "$TEST_SERVER_RSA_PUBLIC_KEY"
  - export SSHPASS=$TEST_SERVER_SSH_PASSWORD
  - sshpass -V
  - sshpass -e scp -o StrictHostKeyChecking=no $PWD/scripts/releaseTestServer.sh u1440721@159.203.33.172:$HOME/init.sh
  - sshpass -e ssh u1440721@159.203.33.172 'chmod +x init.sh'
  - sshpass -e ssh u1440721@159.203.33.172 'sh init.sh'
#  - eval "$(ssh-agent -s)"
#  - ssh-add ~/.ssh/id_rsa
#  - scp -o StrictHostKeyChecking=no $PWD/scripts/releaseTestServer.sh u1440721@159.203.33.172:$HOME/init.sh
#  - ssh u1440721@159.203.33.172 'chmod +x init.sh'
#  - ssh u1440721@159.203.33.172 'sh init.sh'