sudo: required

language: csharp
cache:
  directories:
  - $HOME/packages

services:
  - docker

script:
  - echo $PWD
  - ls
  - export TRAVIS_BUILD_DIRECTORY=$PWD
  - docker build -t webapp:test -f dockerfiles/test .
  - docker run -it -v $HOME/packages:/root/.nuget/packages -v $PWD/publish:/root/publish webapp:test

after_success:
  - cd $TRAVIS_BUILD_DIRECTORY
  - echo $PWD
  - ls
  - docker build -t xaviercl/webapp:latest -f dockerfiles/release .
  - docker login -u="$DOCKER_HUB_USERNAME" -p="$DOCKER_HUB_PASSWORD"
  - docker push xaviercl/webapp:latest